#############################################################################
# Makefile for building: lazyword
# Generated by qmake (2.01a) (Qt 4.5.0) on: Mon Mar 16 10:08:29 2009
# Project:  lazyword.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.5.0/bin/qmake -unix -o Makefile lazyword.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.5.0/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.5.0/include/QtCore -I/usr/local/Trolltech/Qt-4.5.0/include/QtGui -I/usr/local/Trolltech/Qt-4.5.0/include/QtSql -I/usr/local/Trolltech/Qt-4.5.0/include -I. -Iheaders -Isrc/function/headers -Iui -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.5.0/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.5.0/lib -lQtSql -L/usr/local/Trolltech/Qt-4.5.0/lib -pthread -pthread -lQtGui -L/usr/X11R6/lib -pthread -lpng -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.5.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/explain.cpp \
		src/inslib.cpp \
		src/LazyWord.cpp \
		src/main.cpp \
		src/updatelib.cpp \
		src/function/src/getallexp.cpp \
		src/function/src/GetEFromNet.cpp \
		src/function/src/GetSelect.cpp \
		src/function/src/showmessage.cpp moc_explain.cpp \
		moc_inslib.cpp \
		moc_LazyWord.cpp \
		moc_updatelib.cpp \
		moc_getallexp.cpp \
		moc_showmessage.cpp
OBJECTS       = explain.o \
		inslib.o \
		LazyWord.o \
		main.o \
		updatelib.o \
		getallexp.o \
		GetEFromNet.o \
		GetSelect.o \
		showmessage.o \
		moc_explain.o \
		moc_inslib.o \
		moc_LazyWord.o \
		moc_updatelib.o \
		moc_getallexp.o \
		moc_showmessage.o
DIST          = /usr/local/Trolltech/Qt-4.5.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/lex.prf \
		lazyword.pro
QMAKE_TARGET  = lazyword
DESTDIR       = 
TARGET        = lazyword

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_lazywordhelp.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: lazyword.pro  /usr/local/Trolltech/Qt-4.5.0/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.5.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.5.0/lib/libQtSql.prl \
		/usr/local/Trolltech/Qt-4.5.0/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.5.0/lib/libQtGui.prl
	$(QMAKE) -unix -o Makefile lazyword.pro
/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.5.0/lib/libQtSql.prl:
/usr/local/Trolltech/Qt-4.5.0/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.5.0/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile lazyword.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/lazyword1.0.0 || $(MKDIR) .tmp/lazyword1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/lazyword1.0.0/ && $(COPY_FILE) --parents headers/explain.h headers/Initial.h headers/inslib.h headers/LazyWord.h headers/sql.h headers/updatelib.h src/function/headers/getallexp.h src/function/headers/GetEFromNet.h src/function/headers/GetSelect.h src/function/headers/showmessage.h .tmp/lazyword1.0.0/ && $(COPY_FILE) --parents src/explain.cpp src/inslib.cpp src/LazyWord.cpp src/main.cpp src/updatelib.cpp src/function/src/getallexp.cpp src/function/src/GetEFromNet.cpp src/function/src/GetSelect.cpp src/function/src/showmessage.cpp .tmp/lazyword1.0.0/ && $(COPY_FILE) --parents ui/lazywordhelp.ui .tmp/lazyword1.0.0/ && (cd `dirname .tmp/lazyword1.0.0` && $(TAR) lazyword1.0.0.tar lazyword1.0.0 && $(COMPRESS) lazyword1.0.0.tar) && $(MOVE) `dirname .tmp/lazyword1.0.0`/lazyword1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/lazyword1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_explain.cpp moc_inslib.cpp moc_LazyWord.cpp moc_updatelib.cpp moc_getallexp.cpp moc_showmessage.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_explain.cpp moc_inslib.cpp moc_LazyWord.cpp moc_updatelib.cpp moc_getallexp.cpp moc_showmessage.cpp
moc_explain.cpp: headers/explain.h
	/usr/local/Trolltech/Qt-4.5.0/bin/moc $(DEFINES) $(INCPATH) headers/explain.h -o moc_explain.cpp

moc_inslib.cpp: headers/inslib.h
	/usr/local/Trolltech/Qt-4.5.0/bin/moc $(DEFINES) $(INCPATH) headers/inslib.h -o moc_inslib.cpp

moc_LazyWord.cpp: src/function/headers/GetEFromNet.h \
		src/function/headers/showmessage.h \
		ui_lazywordhelp.h \
		headers/inslib.h \
		headers/LazyWord.h
	/usr/local/Trolltech/Qt-4.5.0/bin/moc $(DEFINES) $(INCPATH) headers/LazyWord.h -o moc_LazyWord.cpp

moc_updatelib.cpp: headers/updatelib.h
	/usr/local/Trolltech/Qt-4.5.0/bin/moc $(DEFINES) $(INCPATH) headers/updatelib.h -o moc_updatelib.cpp

moc_getallexp.cpp: src/function/headers/GetEFromNet.h \
		src/function/headers/getallexp.h
	/usr/local/Trolltech/Qt-4.5.0/bin/moc $(DEFINES) $(INCPATH) src/function/headers/getallexp.h -o moc_getallexp.cpp

moc_showmessage.cpp: src/function/headers/showmessage.h
	/usr/local/Trolltech/Qt-4.5.0/bin/moc $(DEFINES) $(INCPATH) src/function/headers/showmessage.h -o moc_showmessage.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_lazywordhelp.h
compiler_uic_clean:
	-$(DEL_FILE) ui_lazywordhelp.h
ui_lazywordhelp.h: ui/lazywordhelp.ui
	/usr/local/Trolltech/Qt-4.5.0/bin/uic ui/lazywordhelp.ui -o ui_lazywordhelp.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

explain.o: src/explain.cpp headers/explain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o explain.o src/explain.cpp

inslib.o: src/inslib.cpp headers/inslib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inslib.o src/inslib.cpp

LazyWord.o: src/LazyWord.cpp headers/LazyWord.h \
		src/function/headers/GetEFromNet.h \
		src/function/headers/showmessage.h \
		ui_lazywordhelp.h \
		headers/inslib.h \
		headers/sql.h \
		src/function/headers/GetSelect.h \
		headers/explain.h \
		headers/updatelib.h \
		src/function/headers/getallexp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LazyWord.o src/LazyWord.cpp

main.o: src/main.cpp headers/LazyWord.h \
		src/function/headers/GetEFromNet.h \
		src/function/headers/showmessage.h \
		ui_lazywordhelp.h \
		headers/inslib.h \
		headers/Initial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

updatelib.o: src/updatelib.cpp headers/updatelib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o updatelib.o src/updatelib.cpp

getallexp.o: src/function/src/getallexp.cpp src/function/headers/getallexp.h \
		src/function/headers/GetEFromNet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getallexp.o src/function/src/getallexp.cpp

GetEFromNet.o: src/function/src/GetEFromNet.cpp src/function/headers/GetEFromNet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GetEFromNet.o src/function/src/GetEFromNet.cpp

GetSelect.o: src/function/src/GetSelect.cpp src/function/headers/GetSelect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GetSelect.o src/function/src/GetSelect.cpp

showmessage.o: src/function/src/showmessage.cpp src/function/headers/showmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o showmessage.o src/function/src/showmessage.cpp

moc_explain.o: moc_explain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_explain.o moc_explain.cpp

moc_inslib.o: moc_inslib.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inslib.o moc_inslib.cpp

moc_LazyWord.o: moc_LazyWord.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LazyWord.o moc_LazyWord.cpp

moc_updatelib.o: moc_updatelib.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_updatelib.o moc_updatelib.cpp

moc_getallexp.o: moc_getallexp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_getallexp.o moc_getallexp.cpp

moc_showmessage.o: moc_showmessage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_showmessage.o moc_showmessage.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

